name: Tests & Lint
on:
  push:
    branches:
      - main
      - add-CI-CD
  pull_request:
    branches:
      - main
      - add-CI-CD

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.1' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.1

      - name: Setup project
        run: make setup

      - name: Check lint
        run: make lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage

      - name: Run test & publish code coverage / CODECLIMATE
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
